{"version":"3.8.2","messages":["\nAn error occurred while loading ./spec/01_has_many_through_spec.rb.\n\u001b[31mFailure/Error: \u001b[0mrequire_relative \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31m./lib/customer.rb\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mLoadError:\u001b[0m\n\u001b[31m  cannot load such file -- /home/voluble-process-0686/ruby-objects-has-many-through-readme-online-web-pt-061019/lib/lib/customer.rb\u001b[0m\n\u001b[36m# ./lib/meal.rb:1:in `require_relative'\u001b[0m\n\u001b[36m# ./lib/meal.rb:1:in `<top (required)>'\u001b[0m\n\u001b[36m# ./spec/spec_helper.rb:1:in `require'\u001b[0m\n\u001b[36m# ./spec/spec_helper.rb:1:in `block in <top (required)>'\u001b[0m\n\u001b[36m# ./spec/spec_helper.rb:1:in `each'\u001b[0m\n\u001b[36m# ./spec/spec_helper.rb:1:in `<top (required)>'\u001b[0m\n\u001b[36m# ./spec/01_has_many_through_spec.rb:1:in `require'\u001b[0m\n\u001b[36m# ./spec/01_has_many_through_spec.rb:1:in `<top (required)>'\u001b[0m\n","No examples found."],"examples":[],"summary":{"duration":0.00050297,"example_count":0,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":2},"summary_line":"0 examples, 0 failures, 2 errors occurred outside of examples"}